### ISSUE TITLE
Dependabot no longer working well for go dependencies

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/gateway-api#2780]
**What happened**:
PRs opened by dependabot do not appear to be running `go mod tidy` and are failing our presubmits.

**What you expected to happen**:
PR opened by dependabot to pass our presubmits.

**Anything else we need to know?**:
Not sure what the solution is here, maybe it's just better dependabot config, or maybe we should look into an alternative like renovate that [appears to have a few more configuration options here](https://docs.renovatebot.com/configuration-options/#postupdateoptions). With that said, I can't find any prior art for running renovate with k8s projects, so it's probably safest to stick with dependabot if we can get it to work.

**Comment by jongwooo** [comment]
Can I work on this issue?

**Comment by jongwooo** [comment]
Currently, the `dependabot.yml` is only tracking for the directory `/`. I think adding few settings for the directories `gwctl/` and `conformance/echo-basic/` will fix this.

https://github.com/kubernetes-sigs/gateway-api/blob/1bd31243c2431a1905b46d73b5d27c6856e9f8a8/.github/dependabot.yml#L3-L15

**Comment by youngnick** [comment]
/assign @jongwooo 

Sounds great, feel free to make a PR!

**Comment by jongwooo** [comment]
Still same problem in #2789

**Comment by robscott** [comment]
> Still same problem in #2789

😢 reopening this for now, though #2786 was still very helpful for other reasons. Open to other potential fixes for this particular problem.

**Comment by sunjayBhatia** [comment]
the issue looks like it is due to there being multiple modules in the repo and the update order of in the case of #2798 between the different modules, the `gwctl` module has an older version of the k8s.io deps than the PR is updating to

**Comment by sunjayBhatia** [comment]
I don't have the right permissions but looks like a dependabot rebase should fix the issue at hand in https://github.com/kubernetes-sigs/gateway-api/pull/2789

**Comment by dprotaso** [comment]
I wonder if dropping the `replace` block in gwctl's go.mod would help. That replace block also prevents people from installing it with `go install`.

I wonder if this is those niche scenarios were commiting a `go.work` file makes sense

**Comment by robscott** [comment]
Unfortunately still failing in #2882

**Comment by rikatz** [comment]
This is still a problem now, but because of workspaces. Dependabot is kinda bad working with tidy and grouped dependencies.

I will check if there are other things we can do with it...
